version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: airman_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-airman}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: airman_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: airman_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-airman}?schema=public
      - PORT=4000
      - JWT_SECRET=airman_super_secret_jwt_key_2026
      - JWT_EXPIRES_IN=90d
      - ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: airman_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api/v1
      - NEXT_PUBLIC_ENCRYPTION_KEY=0123456789abcdef0123456789abcdef
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - api

volumes:

  postgres_data:
